const toolsData = [
      {
        category: "Image Converters",
        tools: [
          { name: "Image To JPG Converter", url: "/image-to-jpg-converter.html", keywords: ["image", "jpg", "converter"] },
          { name: "Image To PNG Converter", url: "/image-to-png-converter.html", keywords: ["image", "png", "converter"] },
          { name: "Image To SVG Converter", url: "/image-to-svg-converter.html", keywords: ["image", "svg", "converter"] },
          { name: "Image To WEBP Converter", url: "/image-to-webp-converter.html", keywords: ["image", "webp", "converter"] },
          { name: "Image To TIFF Converter", url: "/image-to-tiff-converter.html", keywords: ["image", "tiff", "converter"] },
          { name: "Image To HEIC Converter", url: "/image-to-heic-converter.html", keywords: ["image", "heic", "converter"] },
          { name: "Image To PDF Converter", url: "/image-to-pdf-converter.html", keywords: ["image", "pdf", "converter"] },
          { name: "Image To BMP Converter", url: "/image-to-bmp-converter.html", keywords: ["image", "bmp", "converter"] },
          { name: "Image To ICO Converter", url: "/image-to-ico-converter.html", keywords: ["image", "ico", "converter"] },
          { name: "Image To AVIF Converter", url: "/image-to-avif-converter.html", keywords: ["image", "avif", "converter"] },
          { name: "Image To EPS Converter", url: "/image-to-eps-converter.html", keywords: ["image", "eps", "converter"] },
          { name: "Image To PSD Converter", url: "/image-to-psd-converter.html", keywords: ["image", "psd", "converter"] },
          { name: "Image To Base64 Converter", url: "/image-to-base64-converter.html", keywords: ["image", "base64", "converter"] },
          { name: "Image To DXF Converter", url: "/image-to-dxf-converter.html", keywords: ["image", "dxf", "converter"] },
          { name: "Image To EXR Converter", url: "/image-to-exr-converter.html", keywords: ["image", "exr", "converter"] },
          { name: "PDF To Image Converter", url: "/pdf-to-image-converter.html", keywords: ["pdf", "image", "converter"] },
          { name: "Image Resizer Tool", url: "/image-resizer-tool.html", keywords: ["image", "resize", "tool"] },
          { name: "Image Compressor Tool", url: "/image-compressor-tool.html", keywords: ["image", "compress", "tool"] },
          { name: "PSD To Image Converter", url: "/psd-to-image-converter.html", keywords: ["psd", "image", "converter"] },
          { name: "EPS To Image Converter", url: "/eps-to-image-converter.html", keywords: ["eps", "image", "converter"] }
        ]
      },
      {
        category: "Text Tools",
        tools: [
          { name: "Word Counter", url: "/word-counter.html", keywords: ["word", "count", "text"] },
          { name: "Case Converter", url: "/case-converter.html", keywords: ["case", "text", "convert"] },
          { name: "Text To ASCII", url: "/text-to-ascii-converter.html", keywords: ["text", "ascii", "convert"] },
          { name: "Lorem Ipsum Generator", url: "/lorem-ipsum-generator.html", keywords: ["lorem", "ipsum", "text"] },
          { name: "Character Counter", url: "/character-counter.html", keywords: ["character", "count", "text"] },
          { name: "Sort Text", url: "/sort-text.html", keywords: ["sort", "text"] },
          { name: "Find And Replace", url: "/find-and-replace-text.html", keywords: ["find", "replace", "text"] },
          { name: "Reverse List", url: "/reverse-list.html", keywords: ["reverse", "list", "text"] },
          { name: "Difference Checker", url: "/difference-checker.html", keywords: ["difference", "text", "compare"] },
          { name: "Add Prefix/Suffix", url: "/add-prefix-suffix.html", keywords: ["prefix", "suffix", "text"] },
          { name: "Add Line Breaks", url: "/add-line-breaks.html", keywords: ["line", "breaks", "text"] },
          { name: "Remove Line Breaks", url: "/remove-line-breaks.html", keywords: ["remove", "line", "breaks", "text"] },
          { name: "Concatenate Text", url: "/concatenate-text.html", keywords: ["concatenate", "text"] },
          { name: "Split Text", url: "/split-text.html", keywords: ["split", "text"] },
          { name: "Extract Column", url: "/extract-column.html", keywords: ["extract", "column", "text"] },
          { name: "Swap Column", url: "/swap-column.html", keywords: ["swap", "column", "text"] },
          { name: "Reverse Words", url: "/reverse-words.html", keywords: ["reverse", "words", "text"] },
          { name: "Reverse Letters", url: "/reverse-letters.html", keywords: ["reverse", "letters", "text"] },
          { name: "Remove Extra Spaces", url: "/remove-extra-spaces.html", keywords: ["remove", "spaces", "text"] },
          { name: "Remove Duplicate Lines", url: "/remove-duplicate-lines.html", keywords: ["remove", "duplicate", "lines", "text"] },
          { name: "Remove Empty Lines", url: "/remove-empty-lines.html", keywords: ["remove", "empty", "lines", "text"] },
          { name: "Remove Letter Accents", url: "/remove-letter-accents.html", keywords: ["remove", "accents", "text"] },
          { name: "Remove Unwanted Characters", url: "/remove-unwanted-characters.html", keywords: ["remove", "characters", "text"] },
          { name: "Remove Lines Containing/Not Containing", url: "/remove-lines-containing.html", keywords: ["remove", "lines", "text"] },
          { name: "Remove Emojis", url: "/remove-emojis.html", keywords: ["remove", "emojis", "text"] },
          { name: "Strip HTML Tags", url: "/strip-html-tags.html", keywords: ["strip", "html", "text"] },
          { name: "Add Line Numbers", url: "/add-line-numbers.html", keywords: ["add", "line", "numbers", "text"] },
          { name: "Replace Smart/Straight Quotes", url: "/replace-quotes.html", keywords: ["quotes", "smart", "straight", "text"] },
          { name: "Add Commas to Numbers", url: "/add-commas-to-numbers.html", keywords: ["commas", "numbers", "text"] }
        ]
      }
    ];
